language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: gyIweB3I8L4eUiffeD6hrbwGnk+zeZ5EON9ZKWPIUc0sJN9ljauDghWF6zl0XjVD+OfmkCVHjSV5H0TkUnfm5w7Q4PdxApGiBYx2lkOq2Hup0KryB5MsDiRU4454oWb56khOLSD3uICLrI7OtWR8ijRg/WIO0V5x5TFQlzgjncUOBZX1jhWt2DF9lNW8lswa3M8P1yy9j6znFvuCo84r8bmzDLtCDfHx4DwI14dNBLPsfZvnONmjJ69U1Omr4BXzut1T3POrmYSRqRtaTHPT0u+B1E0xDiLy38RkBECGihXas49tzVGx9RpzMPTwl2u5xfsOZAzodSEKRPj7yx1B9/wqzXj7wrdKKjy4Um8GI2JgN+pzHsg52uIiPO2bnuiNEXrrlshO4c52lJOwaLKZHQW8HMedvRmfQhwj/EHuhPohjmMTGFpeysOHbROoednY+dek9Bjje5BH28KbK1MuPXeFB3tcCqGaqijrid11Fy2DcLrbEAWiI6p85w3zZte/J12hGGm/vNhjaOYzNSERvuPyXwRZwbjok36iQRItGnENkp3+ukrw73Zb9XOdLwII5idRJTO+tlQVb7zbq6hjWAbxKmxDZcubZarekbImx7ItbRLfYeeNZZlnca6jKZSSB3qfeD9r92CjBk3Y+KSJEYMq+hGWOEnaBqkJ+LxVCGA=
  app: greatbeer
  on:
    repo: luupanu/Greatbeer
  run: "rake db:migrate"